packages:
  - apps/*
  - examples/*
  - packages/*
allowBuilds:
  esbuild: false
  msw: false

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vitest: 4.1.11
  vite-plus: 0.3.0
  "@vitest/coverage-v8": 4.1.11

overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
blockExoticSubdeps: true
minimumReleaseAge: 1440 # 1 day
strictDepBuilds: true
minimumReleaseAgeExclude:
  - clarity-abitype@0.7.1
