import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    sortImports: true,
    ignorePatterns: [".agents/**", "tools/oxlint/anti-slop/**"],
  },
  lint: {
    categories: {
      correctness: "error",
      nursery: "error",
      perf: "error",
      suspicious: "error",
      pedantic: "error",
      restriction: "error",
      style: "error",
    },
    plugins: ["node", "typescript", "vitest"],
    options: { typeAware: true, typeCheck: true },
    ignorePatterns: [".agents/**", "tools/oxlint/anti-slop/**"],
    jsPlugins: [
      { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
      {
        name: "anti-slop-effect",
        specifier: "./tools/oxlint/anti-slop/effect/index.ts",
      },
    ],
    rules: {
      "sort-imports": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-classes-per-file": "off",
      "max-statements": "off",
      "max-params": "off",
      "require-await": "off",
      "no-ternary": "off",
      "no-magic-numbers": "off",
      "no-warning-comments": "off",
      "new-cap": "off",
      "no-undefined": "off",
      "oxc/no-async-await": "off",
      "typescript/promise-function-async": "off",
      "typescript/explicit-function-return-type": "off",
      "typescript/explicit-module-boundary-types": "off",
      "typescript/prefer-readonly-parameter-types": "off",
      "typescript/strict-boolean-expressions": "off",
      "typescript/consistent-indexed-object-style": "off",
      "unicorn/no-null": "off",
      "func-style": "off",
      "vitest/require-test-timeout": "off",
      "vitest/require-mock-type-parameters": "off",
      "vitest/max-expects": "off",
      "vitest/prefer-to-be-truthy": "off",
      "vitest/prefer-to-be-falsy": "off",
      "vitest/no-hooks": "off",
      "vitest/prefer-import-in-mock": "off",
      "vitest/prefer-expect-assertions": "off",
      "vitest/no-importing-vitest-globals": "off",
      "jest/consistent-test-it": "off",
      "jest/prefer-ending-with-an-expect": "off",

      "sort-keys": "off",
      "one-var": "off",
      "node/no-sync": "off",
      "node/no-top-level-await": "off",
      "vitest/prefer-importing-vitest-globals": "off",
      "vitest/consistent-test-it": "off",
      "vitest/require-hook": "off",
      "no-underscore-dangle": "off",
      "no-await-in-loop": "off",

      "oxc/no-accumulating-spread": "error",
      "anti-slop/no-array-filter-map": "error",
      "anti-slop/no-reduce-accumulator-copy": "error",
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      // Schema-free repo: allow typeof inside boundary type predicates.
      "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-readable-spacing": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",

      "anti-slop-effect/no-manual-effect-error-tag": "error",
      "anti-slop-effect/no-manual-tag-comparison": "error",
      "anti-slop-effect/no-manual-tagged-construction": "error",
      "anti-slop-effect/no-service-constructor-imports": "error",
      "anti-slop-effect/prefer-effect-match": "error",
    },
  },
  test: {
    // Vitest v4 compatibility: preserve mock call history.
    // Remove after tests no longer rely on calls from setup or earlier tests.
    // https://viteplus.dev/guide/vitest-v5#remove-unneeded-compatibility-settings
    // https://vitest.dev/guide/migration/#clearmocks-is-enabled-by-default
    clearMocks: false,
    testTimeout: 60000,
    hookTimeout: 60000,
    exclude: ["**/node_modules/**", "**/dist/**", "repos/**"],
  },
  run: {
    cache: true,
  },
});
