import path from "node:path";

import { defineConfig } from "vite-plus";

export default defineConfig({
  resolve: {
    alias: {
      stacksindex: path.resolve(import.meta.dirname, "packages/stacksindex/src/index.ts"),
    },
  },
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    sortImports: true,
  },
  lint: {
    categories: {
      correctness: "error",
      nursery: "error",
      perf: "error",
      suspicious: "error",
      pedantic: "error",
      restriction: "error",
      style: "error",
    },
    plugins: ["node", "typescript", "vitest"],
    options: { typeAware: true, typeCheck: true },
    rules: {
      "sort-imports": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-classes-per-file": "off",
      "max-statements": "off",
      "max-params": "off",
      "require-await": "off",
      "no-ternary": "off",
      "no-magic-numbers": "off",
      "no-warning-comments": "off",
      "new-cap": "off",
      "no-undefined": "off",
      "oxc/no-async-await": "off",
      "typescript/promise-function-async": "off",
      "typescript/explicit-function-return-type": "off",
      "typescript/explicit-module-boundary-types": "off",
      "typescript/prefer-readonly-parameter-types": "off",
      "typescript/strict-boolean-expressions": "off",
      "typescript/consistent-indexed-object-style": "off",
      "unicorn/no-null": "off",
      "func-style": "off",
      "vitest/require-test-timeout": "off",
      "vitest/require-mock-type-parameters": "off",
      "vitest/prefer-to-be-truthy": "off",
      "vitest/prefer-to-be-falsy": "off",
      "vitest/no-hooks": "off",
      "vitest/prefer-import-in-mock": "off",
      "vitest/prefer-expect-assertions": "off",
      "vitest/no-importing-vitest-globals": "off",
      "jest/consistent-test-it": "off",
      "jest/prefer-ending-with-an-expect": "off",

      "sort-keys": "off",
      "one-var": "off",
      "node/no-sync": "off",
      "node/no-top-level-await": "off",
      "vitest/prefer-importing-vitest-globals": "off",
      "vitest/consistent-test-it": "off",
      "vitest/require-hook": "off",
      "no-underscore-dangle": "off",
      "no-await-in-loop": "off",
      "typescript/await-thenable": "off",
      "typescript/no-unsafe-member-access": "off",
      "typescript/no-unsafe-call": "off",
      "typescript/no-unsafe-assignment": "off",
      "typescript/no-unsafe-argument": "off",
      "typescript/no-unsafe-return": "off",
      "typescript/no-unsafe-type-assertion": "off",
      "typescript/no-explicit-any": "off",
      "typescript/no-confusing-void-expression": "off",
      "typescript/no-unnecessary-condition": "off",
      "typescript/consistent-return": "off",
      "typescript/no-unnecessary-type-parameters": "off",
      "typescript/explicit-member-accessibility": "off",
      "typescript/prefer-nullish-coalescing": "off",
      "func-names": "off",
      "no-nested-ternary": "off",
      "no-undef": "off",
      "init-declarations": "off",
      "id-length": "off",
      "typescript/no-empty-interface": "off",
      "typescript/no-empty-object-type": "off",
      "typescript/no-unnecessary-type-assertion": "off",
      "no-shadow": "off",
      "no-use-before-define": "off",
      "vitest/expect-expect": "off",
    },
  },
  test: {
    setupFiles: ["./packages/stacksindex/src/test-utils/vitest-setup.ts"],
    testTimeout: 60000,
    hookTimeout: 60000,
    exclude: ["**/node_modules/**", "**/dist/**", "repos/**"],
  },
  run: {
    cache: true,
  },
});
