name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Don't use voidzero-dev/setup-vp as for some reason the OIDC publishing is broken when using it
      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v2
        with:
          version-script: pnpm run version
          publish-script: pnpm run release
          commit-message: "chore: release"
          pr-title: "chore: create new release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
